name: pushmetrics

on:
  pull_request:
    types:
      - labeled
      
jobs:
  send_keptn_event:
    runs-on: ubuntu-latest
    name: Push Metrics to Keptn
    steps:
    - name: Send Keptn Event
      id: send-keptn-event
      uses: keptn/gh-action-send-event@main
      with:
        keptnApiUrl: ${{ secrets.KEPTN_API_URL }}
        keptnApiToken: ${{ secrets.KEPTN_API_TOKEN }}
        event: |
          {
            "data": {
                       "labels": {
                                   "runBy": "adam_gardner",
                                  "team": "innovation"
                                },
                      "label_confidence_data": "{ \"${{ github.event.label.name }}\": 0.980 }",
                     "project": "engine3",
                     "service": "tools",
                     "stage": "dev"
                    },
             "source": "GitHub",
             "specversion": "1.0",
             "type": "sh.keptn.event.dev.pushmetrics.triggered"
           }
